/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legrosdebrouillard;

import TSPModel_PtiDeb.TSPModel_PtiDeb;
import java.awt.Component;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.DefaultGraph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swingViewer.ViewPanel;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author Thomas
 */
public class Plateau extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBandeau = new javax.swing.JPanel();
        buttonPlay = new javax.swing.JToggleButton();
        buttonLoad = new javax.swing.JToggleButton();
        buttonQuit = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        panelLayout = new javax.swing.JPanel();
        panelAcceuilMain = new javax.swing.JPanel();
        panelAcceuil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        panelJeuMain = new javax.swing.JPanel();
        panelJeu = new javax.swing.JPanel();
        buttonArretJeu = new javax.swing.JToggleButton();
        buttonPlayPauseJeu = new javax.swing.JToggleButton();
        buttonAvanceRapideJeu = new javax.swing.JToggleButton();
        buttonRetourRapideJeu = new javax.swing.JToggleButton();
        buttonRecommencerJeu = new javax.swing.JToggleButton();
        bestGraph = new javax.swing.JPanel();
        currentGraph = new javax.swing.JPanel();
        panelChargerMain = new javax.swing.JPanel();
        panelCharger = new javax.swing.JPanel();
        jToggleButton7 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/play.png"))); // NOI18N
        buttonPlay.setBorder(null);
        buttonPlay.setBorderPainted(false);
        buttonPlay.setContentAreaFilled(false);
        buttonPlay.setFocusPainted(false);
        buttonPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPlayMouseClicked(evt);
            }
        });

        buttonLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        buttonLoad.setBorder(null);
        buttonLoad.setBorderPainted(false);
        buttonLoad.setContentAreaFilled(false);
        buttonLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoadMouseClicked(evt);
            }
        });
        buttonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoadActionPerformed(evt);
            }
        });

        buttonQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        buttonQuit.setBorder(null);
        buttonQuit.setBorderPainted(false);
        buttonQuit.setContentAreaFilled(false);
        buttonQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonQuitMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBandeauLayout = new javax.swing.GroupLayout(panelBandeau);
        panelBandeau.setLayout(panelBandeauLayout);
        panelBandeauLayout.setHorizontalGroup(
            panelBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBandeauLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(buttonLoad)
                .addGap(308, 308, 308)
                .addComponent(buttonQuit)
                .addGap(60, 60, 60))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBandeauLayout.setVerticalGroup(
            panelBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBandeauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonQuit)
                    .addComponent(buttonPlay)
                    .addComponent(buttonLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonLoad.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(panelBandeau, java.awt.BorderLayout.PAGE_START);

        panelLayout.setBackground(new java.awt.Color(255, 255, 255));

        panelAcceuilMain.setBackground(new java.awt.Color(255, 255, 255));
        panelAcceuilMain.setLayout(new java.awt.CardLayout());

        panelAcceuil.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Bienvenu sur le plateau de jeu des petits débrouillards ! ");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Pour jouer cliquer sur les icones en haut !");

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graphe.png"))); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelAcceuilLayout = new javax.swing.GroupLayout(panelAcceuil);
        panelAcceuil.setLayout(panelAcceuilLayout);
        panelAcceuilLayout.setHorizontalGroup(
            panelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAcceuilLayout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addGroup(panelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        panelAcceuilLayout.setVerticalGroup(
            panelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcceuilLayout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(109, 109, 109))
        );

        panelAcceuilMain.add(panelAcceuil, "card2");

        panelJeuMain.setBackground(new java.awt.Color(255, 255, 255));
        panelJeuMain.setLayout(new java.awt.CardLayout());

        panelJeu.setBackground(new java.awt.Color(255, 255, 255));

        buttonArretJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arret.png"))); // NOI18N
        buttonArretJeu.setBorderPainted(false);
        buttonArretJeu.setContentAreaFilled(false);

        buttonPlayPauseJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pause.png"))); // NOI18N
        buttonPlayPauseJeu.setBorderPainted(false);
        buttonPlayPauseJeu.setContentAreaFilled(false);
        buttonPlayPauseJeu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPlayPauseJeuMouseClicked(evt);
            }
        });

        buttonAvanceRapideJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        buttonAvanceRapideJeu.setBorderPainted(false);
        buttonAvanceRapideJeu.setContentAreaFilled(false);
        buttonAvanceRapideJeu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAvanceRapideJeuMouseClicked(evt);
            }
        });

        buttonRetourRapideJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/moins.png"))); // NOI18N
        buttonRetourRapideJeu.setBorderPainted(false);
        buttonRetourRapideJeu.setContentAreaFilled(false);
        buttonRetourRapideJeu.setDisabledIcon(null);
        buttonRetourRapideJeu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRetourRapideJeuMouseClicked(evt);
            }
        });

        buttonRecommencerJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/restart.png"))); // NOI18N
        buttonRecommencerJeu.setBorderPainted(false);
        buttonRecommencerJeu.setContentAreaFilled(false);

        bestGraph.setBackground(new java.awt.Color(255, 255, 255));
        bestGraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bestGraph.setLayout(new java.awt.BorderLayout());

        currentGraph.setBackground(new java.awt.Color(255, 255, 255));
        currentGraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currentGraph.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelJeuLayout = new javax.swing.GroupLayout(panelJeu);
        panelJeu.setLayout(panelJeuLayout);
        panelJeuLayout.setHorizontalGroup(
            panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJeuLayout.createSequentialGroup()
                .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJeuLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(buttonRetourRapideJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJeuLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(currentGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJeuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPlayPauseJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonArretJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAvanceRapideJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRecommencerJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJeuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bestGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelJeuLayout.setVerticalGroup(
            panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentGraph, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addComponent(bestGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonRecommencerJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonAvanceRapideJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonArretJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonPlayPauseJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonRetourRapideJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        panelJeuMain.add(panelJeu, "card2");

        panelChargerMain.setBackground(new java.awt.Color(255, 255, 255));
        panelChargerMain.setLayout(new java.awt.CardLayout());

        panelCharger.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton7.setText("load");

        javax.swing.GroupLayout panelChargerLayout = new javax.swing.GroupLayout(panelCharger);
        panelCharger.setLayout(panelChargerLayout);
        panelChargerLayout.setHorizontalGroup(
            panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelChargerLayout.createSequentialGroup()
                    .addGap(0, 500, Short.MAX_VALUE)
                    .addComponent(jToggleButton7)
                    .addGap(0, 500, Short.MAX_VALUE)))
        );
        panelChargerLayout.setVerticalGroup(
            panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelChargerLayout.createSequentialGroup()
                    .addGap(0, 411, Short.MAX_VALUE)
                    .addComponent(jToggleButton7)
                    .addGap(0, 411, Short.MAX_VALUE)))
        );

        panelChargerMain.add(panelCharger, "card2");

        javax.swing.GroupLayout panelLayoutLayout = new javax.swing.GroupLayout(panelLayout);
        panelLayout.setLayout(panelLayoutLayout);
        panelLayoutLayout.setHorizontalGroup(
            panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAcceuilMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelJeuMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelChargerMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayoutLayout.setVerticalGroup(
            panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAcceuilMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayoutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelJeuMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelChargerMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayMouseClicked
        panelLayout.removeAll();
        panelLayout.add(panelJeuMain);
        model = new TSPModel_PtiDeb(this);
       
        try {
            FileReader fr = new FileReader(path);
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                model.addPoint(Integer.parseInt(values[0]), Integer.parseInt(values[1]), Integer.parseInt(values[2]));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        panelLayout.repaint();
        panelLayout.revalidate();
        remplirGraph();
    }//GEN-LAST:event_buttonPlayMouseClicked

    private void buttonLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoadActionPerformed
       
    }//GEN-LAST:event_buttonLoadActionPerformed

    private void buttonLoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoadMouseClicked
        panelLayout.removeAll();
        panelLayout.add(panelChargerMain);
        panelLayout.repaint();
        panelLayout.revalidate();
    }//GEN-LAST:event_buttonLoadMouseClicked

    private void buttonQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonQuitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_buttonQuitMouseClicked

    private void buttonPlayPauseJeuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPlayPauseJeuMouseClicked
        if(!begin) {
            begin = true ;
            thread = new Thread(model) ;
            thread.start();
            return ;
        }
       
        if(stop) {
            stop = false ;
            System.out.println(stop);
            model.setPause(true) ;
            return ;
        }
        else {
            stop = true ;
            System.out.println(stop);
            
            synchronized(model) {
                model.setPause(false) ;
                model.notify();
            }
            
            return ;
        }
    }//GEN-LAST:event_buttonPlayPauseJeuMouseClicked

    private void buttonRetourRapideJeuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRetourRapideJeuMouseClicked
       this.wait += 200 ;
    }//GEN-LAST:event_buttonRetourRapideJeuMouseClicked

    private void buttonAvanceRapideJeuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAvanceRapideJeuMouseClicked
        this.wait -= 200 ;
    }//GEN-LAST:event_buttonAvanceRapideJeuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plateau().setVisible(true);
            }
        });
    }
    
    private void lireFichierCSV() {
        Graph tmp = new SingleGraph("test") ;
        
        try {
            FileReader fr = new FileReader(path);
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                Node node = this.best.addNode(String.valueOf(Integer.parseInt(values[0]))) ;
                Node nodeC = this.current.addNode(String.valueOf(Integer.parseInt(values[0]))) ;
                node.setAttribute("xy", Integer.parseInt(values[1]), Integer.parseInt(values[2]));
                nodeC.setAttribute("xy", Integer.parseInt(values[1]), Integer.parseInt(values[2]));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void remplirGraph() {
        this.lireFichierCSV();
        this.best.addAttribute("ui.quality");
        this.best.addAttribute("ui.antialias");
        this.current.addAttribute("ui.quality");
        this.current.addAttribute("ui.antialias");
        
        this.best.setAutoCreate(true);
        this.best.setStrict(true);
        Viewer viewer = new Viewer(this.best, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        viewer.addDefaultView(false);
        ViewPanel viewPanel = viewer.addDefaultView(false);
        bestGraph.add(viewPanel);
        panelJeu.add(bestGraph) ;
        panelJeuMain.add(panelJeu) ;
        panelLayout.add(panelJeuMain);
        
        this.current.setAutoCreate(true);
        this.current.setStrict(true);
        Viewer viewerV2 = new Viewer(this.current, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        viewerV2.addDefaultView(false);
        ViewPanel viewPanelV2 = viewerV2.addDefaultView(false);
        currentGraph.add(viewPanelV2);
        panelJeu.add(currentGraph) ;
        panelJeuMain.add(panelJeu) ;
        panelLayout.add(panelJeuMain);
        
        this.add(panelLayout);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof TSPModel_PtiDeb) {
            TSPModel_PtiDeb model = (TSPModel_PtiDeb) o;
            int id = model.getSegmentID();
            int p1 = model.getSegmentP1();
            int p2 = model.getSegmentP2();
            switch (model.getAction()) {
                case Add:
                    addToGraph(id, p1, p2);
                    break;
                case Remove:
                    removeFromGraph(id);
                    break;
                case NewBest:
                    updateBest();
                    break;
                case Finish:
                    finish();
                    break;
            }
            try {
                Thread.sleep(wait);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
     public void addToGraph(int id, int p1, int p2) {
        this.current.addEdge(Integer.toString(id), Integer.toString(p1), Integer.toString(p2));
    }

    public void removeFromGraph(int id) {
        this.current.removeEdge(Integer.toString(id));
    }

    public void updateBest() {
        while(this.best.getEdgeCount() > 0) {
            this.best.removeEdge(0);
        }
        for (Edge edge : this.current.getEachEdge()) {
            this.best.addEdge(edge.getId(), edge.getSourceNode().getId(), edge.getTargetNode().getId());
        }
    }

    public void finish() {
        System.out.println("Fini");
        JOptionPane.showMessageDialog(null,"Fini");
    }
    
    private Integer wait = 300 ;
    private boolean begin = false ;
    private boolean stop = true ;
    TSPModel_PtiDeb model ;
    Thread thread ;
    private String path = "F:\\Documents\\NetBeansProjects\\LeGrosDebrouillard\\src\\CSV\\Default.csv" ;
    private Graph current = new SingleGraph("current");
    private Graph best = new SingleGraph("best");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bestGraph;
    private javax.swing.JToggleButton buttonArretJeu;
    private javax.swing.JToggleButton buttonAvanceRapideJeu;
    private javax.swing.JToggleButton buttonLoad;
    private javax.swing.JToggleButton buttonPlay;
    private javax.swing.JToggleButton buttonPlayPauseJeu;
    private javax.swing.JToggleButton buttonQuit;
    private javax.swing.JToggleButton buttonRecommencerJeu;
    private javax.swing.JToggleButton buttonRetourRapideJeu;
    private javax.swing.JPanel currentGraph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JPanel panelAcceuil;
    private javax.swing.JPanel panelAcceuilMain;
    private javax.swing.JPanel panelBandeau;
    private javax.swing.JPanel panelCharger;
    private javax.swing.JPanel panelChargerMain;
    private javax.swing.JPanel panelJeu;
    private javax.swing.JPanel panelJeuMain;
    private javax.swing.JPanel panelLayout;
    // End of variables declaration//GEN-END:variables
}
