/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legrosdebrouillard;

import TSPModel_PtiDeb.TSPModel_PtiDeb;
import java.awt.Component;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Collection;
import java.util.Iterator;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.graphstream.graph.Edge;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.DefaultGraph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swingViewer.ViewPanel;
import org.graphstream.ui.view.Viewer;

/**
 *
 * @author Thomas
 */
public class Plateau extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form Plateau
     */
    public Plateau() {
        initComponents();
        panelLayout.removeAll();
        panelLayout.add(panelAcceuilMain);
        panelLayout.repaint();
        panelLayout.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBandeau = new javax.swing.JPanel();
        buttonPlay = new javax.swing.JToggleButton();
        buttonLoad = new javax.swing.JToggleButton();
        buttonQuit = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        buttonCreate = new javax.swing.JToggleButton();
        panelLayout = new javax.swing.JPanel();
        panelAcceuilMain = new javax.swing.JPanel();
        panelAcceuil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        panelJeuMain = new javax.swing.JPanel();
        panelJeu = new javax.swing.JPanel();
        buttonArretJeu = new javax.swing.JToggleButton();
        buttonPlayPauseJeu = new javax.swing.JToggleButton();
        buttonAvanceRapideJeu = new javax.swing.JToggleButton();
        buttonRetourRapideJeu = new javax.swing.JToggleButton();
        buttonRecommencerJeu = new javax.swing.JToggleButton();
        bestGraph = new javax.swing.JPanel();
        currentGraph = new javax.swing.JPanel();
        panelChargerMain = new javax.swing.JPanel();
        panelCharger = new javax.swing.JPanel();
        x1x1 = new javax.swing.JRadioButton();
        x2x1 = new javax.swing.JRadioButton();
        x3x1 = new javax.swing.JRadioButton();
        x6x1 = new javax.swing.JRadioButton();
        x5x1 = new javax.swing.JRadioButton();
        x4x1 = new javax.swing.JRadioButton();
        x9x1 = new javax.swing.JRadioButton();
        x8x1 = new javax.swing.JRadioButton();
        x7x1 = new javax.swing.JRadioButton();
        x9x2 = new javax.swing.JRadioButton();
        x8x2 = new javax.swing.JRadioButton();
        x7x2 = new javax.swing.JRadioButton();
        x6x2 = new javax.swing.JRadioButton();
        x5x2 = new javax.swing.JRadioButton();
        x4x2 = new javax.swing.JRadioButton();
        x3x2 = new javax.swing.JRadioButton();
        x2x2 = new javax.swing.JRadioButton();
        x1x2 = new javax.swing.JRadioButton();
        x9x3 = new javax.swing.JRadioButton();
        x8x3 = new javax.swing.JRadioButton();
        x7x3 = new javax.swing.JRadioButton();
        x6x3 = new javax.swing.JRadioButton();
        x5x3 = new javax.swing.JRadioButton();
        x4x3 = new javax.swing.JRadioButton();
        x3x3 = new javax.swing.JRadioButton();
        x2x3 = new javax.swing.JRadioButton();
        x1x3 = new javax.swing.JRadioButton();
        x9x4 = new javax.swing.JRadioButton();
        x8x4 = new javax.swing.JRadioButton();
        x7x4 = new javax.swing.JRadioButton();
        x6x4 = new javax.swing.JRadioButton();
        x5x4 = new javax.swing.JRadioButton();
        x4x4 = new javax.swing.JRadioButton();
        x3x4 = new javax.swing.JRadioButton();
        x2x4 = new javax.swing.JRadioButton();
        x1x4 = new javax.swing.JRadioButton();
        x9x5 = new javax.swing.JRadioButton();
        x8x5 = new javax.swing.JRadioButton();
        x7x5 = new javax.swing.JRadioButton();
        x6x5 = new javax.swing.JRadioButton();
        x5x5 = new javax.swing.JRadioButton();
        x4x5 = new javax.swing.JRadioButton();
        x3x5 = new javax.swing.JRadioButton();
        x2x5 = new javax.swing.JRadioButton();
        x1x5 = new javax.swing.JRadioButton();
        x9x6 = new javax.swing.JRadioButton();
        x8x6 = new javax.swing.JRadioButton();
        x7x6 = new javax.swing.JRadioButton();
        x6x6 = new javax.swing.JRadioButton();
        x5x6 = new javax.swing.JRadioButton();
        x4x6 = new javax.swing.JRadioButton();
        x3x6 = new javax.swing.JRadioButton();
        x2x6 = new javax.swing.JRadioButton();
        x1x6 = new javax.swing.JRadioButton();
        x9x7 = new javax.swing.JRadioButton();
        x8x7 = new javax.swing.JRadioButton();
        x7x7 = new javax.swing.JRadioButton();
        x6x7 = new javax.swing.JRadioButton();
        x5x7 = new javax.swing.JRadioButton();
        x4x7 = new javax.swing.JRadioButton();
        x3x7 = new javax.swing.JRadioButton();
        x2x7 = new javax.swing.JRadioButton();
        x1x7 = new javax.swing.JRadioButton();
        x9x8 = new javax.swing.JRadioButton();
        x8x8 = new javax.swing.JRadioButton();
        x7x8 = new javax.swing.JRadioButton();
        x6x8 = new javax.swing.JRadioButton();
        x5x8 = new javax.swing.JRadioButton();
        x4x8 = new javax.swing.JRadioButton();
        x3x8 = new javax.swing.JRadioButton();
        x2x8 = new javax.swing.JRadioButton();
        x1x8 = new javax.swing.JRadioButton();
        x9x9 = new javax.swing.JRadioButton();
        x8x9 = new javax.swing.JRadioButton();
        x7x9 = new javax.swing.JRadioButton();
        x6x9 = new javax.swing.JRadioButton();
        x5x9 = new javax.swing.JRadioButton();
        x4x9 = new javax.swing.JRadioButton();
        x3x9 = new javax.swing.JRadioButton();
        x2x9 = new javax.swing.JRadioButton();
        x1x9 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        buttonCreerCVS = new javax.swing.JToggleButton();
        textFieldName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        panelCreateMain = new javax.swing.JPanel();
        panelCreate = new javax.swing.JPanel();
        fileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBandeau.setBackground(java.awt.Color.lightGray);

        buttonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/play.png"))); // NOI18N
        buttonPlay.setBorder(null);
        buttonPlay.setBorderPainted(false);
        buttonPlay.setContentAreaFilled(false);
        buttonPlay.setFocusPainted(false);
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBandeauButtonPlay(evt);
            }
        });

        buttonLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        buttonLoad.setBorder(null);
        buttonLoad.setBorderPainted(false);
        buttonLoad.setContentAreaFilled(false);
        buttonLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBandeauButtonLoad(evt);
            }
        });

        buttonQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        buttonQuit.setBorder(null);
        buttonQuit.setBorderPainted(false);
        buttonQuit.setContentAreaFilled(false);
        buttonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBandeauButtonQuit(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        buttonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/create-ConvertImage.png"))); // NOI18N
        buttonCreate.setBorder(null);
        buttonCreate.setBorderPainted(false);
        buttonCreate.setContentAreaFilled(false);
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickBandeauButtonCreate(evt);
            }
        });

        javax.swing.GroupLayout panelBandeauLayout = new javax.swing.GroupLayout(panelBandeau);
        panelBandeau.setLayout(panelBandeauLayout);
        panelBandeauLayout.setHorizontalGroup(
            panelBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBandeauLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(buttonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(buttonCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(buttonLoad)
                .addGap(195, 195, 195)
                .addComponent(buttonQuit)
                .addGap(60, 60, 60))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBandeauLayout.setVerticalGroup(
            panelBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBandeauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBandeauLayout.createSequentialGroup()
                        .addGroup(panelBandeauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonQuit)
                            .addComponent(buttonLoad)
                            .addComponent(buttonPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(buttonCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonLoad.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(panelBandeau, java.awt.BorderLayout.PAGE_START);

        panelLayout.setBackground(new java.awt.Color(255, 255, 255));

        panelAcceuilMain.setBackground(new java.awt.Color(255, 255, 255));
        panelAcceuilMain.setLayout(new java.awt.CardLayout());

        panelAcceuil.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Bienvenu sur le plateau de jeu des petits débrouillards ! ");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Pour jouer cliquer sur les icones en haut !");

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/graphe.png"))); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panelAcceuilLayout = new javax.swing.GroupLayout(panelAcceuil);
        panelAcceuil.setLayout(panelAcceuilLayout);
        panelAcceuilLayout.setHorizontalGroup(
            panelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAcceuilLayout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addGroup(panelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        panelAcceuilLayout.setVerticalGroup(
            panelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAcceuilLayout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(109, 109, 109))
        );

        panelAcceuilMain.add(panelAcceuil, "card2");

        panelJeuMain.setBackground(new java.awt.Color(255, 255, 255));
        panelJeuMain.setLayout(new java.awt.CardLayout());

        panelJeu.setBackground(new java.awt.Color(255, 255, 255));

        buttonArretJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arret.png"))); // NOI18N
        buttonArretJeu.setBorderPainted(false);
        buttonArretJeu.setContentAreaFilled(false);
        buttonArretJeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonArretJeuActionPerformed(evt);
            }
        });

        buttonPlayPauseJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/play.png"))); // NOI18N
        buttonPlayPauseJeu.setBorderPainted(false);
        buttonPlayPauseJeu.setContentAreaFilled(false);
        buttonPlayPauseJeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickPlayPauseButton(evt);
            }
        });

        buttonAvanceRapideJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        buttonAvanceRapideJeu.setBorderPainted(false);
        buttonAvanceRapideJeu.setContentAreaFilled(false);
        buttonAvanceRapideJeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickButtonAvanceRapide(evt);
            }
        });

        buttonRetourRapideJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/moins.png"))); // NOI18N
        buttonRetourRapideJeu.setBorderPainted(false);
        buttonRetourRapideJeu.setContentAreaFilled(false);
        buttonRetourRapideJeu.setDisabledIcon(null);
        buttonRetourRapideJeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickRetourRapide(evt);
            }
        });

        buttonRecommencerJeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/restart.png"))); // NOI18N
        buttonRecommencerJeu.setBorderPainted(false);
        buttonRecommencerJeu.setContentAreaFilled(false);
        buttonRecommencerJeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRecommencerJeuActionPerformed(evt);
            }
        });

        bestGraph.setBackground(new java.awt.Color(255, 255, 255));
        bestGraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bestGraph.setLayout(new java.awt.BorderLayout());

        currentGraph.setBackground(new java.awt.Color(255, 255, 255));
        currentGraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currentGraph.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelJeuLayout = new javax.swing.GroupLayout(panelJeu);
        panelJeu.setLayout(panelJeuLayout);
        panelJeuLayout.setHorizontalGroup(
            panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJeuLayout.createSequentialGroup()
                .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJeuLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(buttonRetourRapideJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJeuLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(currentGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelJeuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPlayPauseJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonArretJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAvanceRapideJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRecommencerJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelJeuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(bestGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelJeuLayout.setVerticalGroup(
            panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentGraph, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                    .addComponent(bestGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonRecommencerJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAvanceRapideJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonArretJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRetourRapideJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonPlayPauseJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        panelJeuMain.add(panelJeu, "card2");

        panelChargerMain.setBackground(new java.awt.Color(255, 255, 255));
        panelChargerMain.setLayout(new java.awt.CardLayout());

        panelCharger.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("3");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("4");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("5");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("6");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("7");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("8");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("9");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("2");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("3");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("4");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("5");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("6");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("7");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("8");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("9");

        buttonCreerCVS.setText("Créer fichier CSV");
        buttonCreerCVS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreerCVSActionPerformed(evt);
            }
        });

        textFieldName.setToolTipText("");

        jLabel21.setText("Entrer un nom de fichier");

        jLabel22.setText("                                             Vous pouvez créer votre progre graph !");

        jLabel23.setText("                                                Cliquez sur les point que vous voullez mettre dans votre graph ! rien de plus simple");

        javax.swing.GroupLayout panelChargerLayout = new javax.swing.GroupLayout(panelCharger);
        panelCharger.setLayout(panelChargerLayout);
        panelChargerLayout.setHorizontalGroup(
            panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChargerLayout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChargerLayout.createSequentialGroup()
                .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelChargerLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(x5x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(x6x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(x4x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(x2x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(x3x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(x8x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(x9x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(x7x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(x1x1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x5x2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x6x2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x4x2))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x2x2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x3x2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x1x2))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x8x2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x9x2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x7x2))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x5x3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x6x3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x4x3))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x2x3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x3x3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x1x3))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x8x3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x9x3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x7x3))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChargerLayout.createSequentialGroup()
                                .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelChargerLayout.createSequentialGroup()
                                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(x5x4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x6x4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x4x4))
                                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(x2x4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x3x4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x1x4))
                                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(x8x4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x9x4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x7x4))
                                            .addComponent(jLabel6))
                                        .addGap(70, 70, 70)
                                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(x5x5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x6x5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x4x5))
                                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(x2x5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x3x5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x1x5))
                                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(x8x5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x9x5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x7x5))
                                            .addComponent(jLabel7)))
                                    .addComponent(jLabel21))
                                .addGap(70, 70, 70)
                                .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(x5x6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(x6x6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(x4x6))
                                    .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(x2x6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(x3x6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(x1x6))
                                    .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(x8x6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(x9x6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(x7x6))))
                            .addComponent(buttonCreerCVS))
                        .addGap(70, 70, 70)
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x5x7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x6x7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x4x7))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x2x7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x3x7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x1x7))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x8x7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x9x7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x7x7))
                            .addComponent(jLabel9))
                        .addGap(70, 70, 70)
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x5x8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x6x8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x4x8))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x2x8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x3x8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x1x8))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x8x8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x9x8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x7x8))
                            .addComponent(jLabel10))
                        .addGap(70, 70, 70)
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x5x9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x6x9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x4x9))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x2x9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x3x9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x1x9))
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(x8x9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x9x9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(x7x9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelChargerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(150, 150, 150))
        );
        panelChargerLayout.setVerticalGroup(
            panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChargerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChargerLayout.createSequentialGroup()
                        .addComponent(x9x9)
                        .addGap(45, 45, 45)
                        .addComponent(x8x9)
                        .addGap(45, 45, 45)
                        .addComponent(x7x9)
                        .addGap(45, 45, 45)
                        .addComponent(x6x9)
                        .addGap(45, 45, 45)
                        .addComponent(x5x9)
                        .addGap(45, 45, 45)
                        .addComponent(x4x9)
                        .addGap(45, 45, 45)
                        .addComponent(x3x9)
                        .addGap(45, 45, 45)
                        .addComponent(x2x9)
                        .addGap(45, 45, 45)
                        .addComponent(x1x9))
                    .addGroup(panelChargerLayout.createSequentialGroup()
                        .addComponent(x9x8)
                        .addGap(45, 45, 45)
                        .addComponent(x8x8)
                        .addGap(45, 45, 45)
                        .addComponent(x7x8)
                        .addGap(45, 45, 45)
                        .addComponent(x6x8)
                        .addGap(45, 45, 45)
                        .addComponent(x5x8)
                        .addGap(45, 45, 45)
                        .addComponent(x4x8)
                        .addGap(45, 45, 45)
                        .addComponent(x3x8)
                        .addGap(45, 45, 45)
                        .addComponent(x2x8)
                        .addGap(45, 45, 45)
                        .addComponent(x1x8))
                    .addGroup(panelChargerLayout.createSequentialGroup()
                        .addComponent(x9x3)
                        .addGap(45, 45, 45)
                        .addComponent(x8x3)
                        .addGap(45, 45, 45)
                        .addComponent(x7x3)
                        .addGap(45, 45, 45)
                        .addComponent(x6x3)
                        .addGap(45, 45, 45)
                        .addComponent(x5x3)
                        .addGap(45, 45, 45)
                        .addComponent(x4x3)
                        .addGap(45, 45, 45)
                        .addComponent(x3x3)
                        .addGap(45, 45, 45)
                        .addComponent(x2x3)
                        .addGap(45, 45, 45)
                        .addComponent(x1x3))
                    .addGroup(panelChargerLayout.createSequentialGroup()
                        .addComponent(x9x4)
                        .addGap(45, 45, 45)
                        .addComponent(x8x4)
                        .addGap(45, 45, 45)
                        .addComponent(x7x4)
                        .addGap(45, 45, 45)
                        .addComponent(x6x4)
                        .addGap(45, 45, 45)
                        .addComponent(x5x4)
                        .addGap(45, 45, 45)
                        .addComponent(x4x4)
                        .addGap(45, 45, 45)
                        .addComponent(x3x4)
                        .addGap(45, 45, 45)
                        .addComponent(x2x4)
                        .addGap(45, 45, 45)
                        .addComponent(x1x4))
                    .addGroup(panelChargerLayout.createSequentialGroup()
                        .addComponent(x9x5)
                        .addGap(45, 45, 45)
                        .addComponent(x8x5)
                        .addGap(45, 45, 45)
                        .addComponent(x7x5)
                        .addGap(45, 45, 45)
                        .addComponent(x6x5)
                        .addGap(45, 45, 45)
                        .addComponent(x5x5)
                        .addGap(45, 45, 45)
                        .addComponent(x4x5)
                        .addGap(45, 45, 45)
                        .addComponent(x3x5)
                        .addGap(45, 45, 45)
                        .addComponent(x2x5)
                        .addGap(45, 45, 45)
                        .addComponent(x1x5))
                    .addGroup(panelChargerLayout.createSequentialGroup()
                        .addComponent(x9x6)
                        .addGap(45, 45, 45)
                        .addComponent(x8x6)
                        .addGap(45, 45, 45)
                        .addComponent(x7x6)
                        .addGap(45, 45, 45)
                        .addComponent(x6x6)
                        .addGap(45, 45, 45)
                        .addComponent(x5x6)
                        .addGap(45, 45, 45)
                        .addComponent(x4x6)
                        .addGap(45, 45, 45)
                        .addComponent(x3x6)
                        .addGap(45, 45, 45)
                        .addComponent(x2x6)
                        .addGap(45, 45, 45)
                        .addComponent(x1x6))
                    .addGroup(panelChargerLayout.createSequentialGroup()
                        .addComponent(x9x7)
                        .addGap(45, 45, 45)
                        .addComponent(x8x7)
                        .addGap(45, 45, 45)
                        .addComponent(x7x7)
                        .addGap(45, 45, 45)
                        .addComponent(x6x7)
                        .addGap(45, 45, 45)
                        .addComponent(x5x7)
                        .addGap(45, 45, 45)
                        .addComponent(x4x7)
                        .addGap(45, 45, 45)
                        .addComponent(x3x7)
                        .addGap(45, 45, 45)
                        .addComponent(x2x7)
                        .addGap(45, 45, 45)
                        .addComponent(x1x7))
                    .addGroup(panelChargerLayout.createSequentialGroup()
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChargerLayout.createSequentialGroup()
                                .addComponent(x9x2)
                                .addGap(45, 45, 45)
                                .addComponent(x8x2)
                                .addGap(45, 45, 45)
                                .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelChargerLayout.createSequentialGroup()
                                        .addComponent(x7x2)
                                        .addGap(45, 45, 45)
                                        .addComponent(x6x2)
                                        .addGap(45, 45, 45)
                                        .addComponent(x5x2)
                                        .addGap(45, 45, 45)
                                        .addComponent(x4x2)
                                        .addGap(45, 45, 45)
                                        .addComponent(x3x2)
                                        .addGap(45, 45, 45)
                                        .addComponent(x2x2))
                                    .addGroup(panelChargerLayout.createSequentialGroup()
                                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(panelChargerLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelChargerLayout.createSequentialGroup()
                                                .addComponent(x7x1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(x6x1)))
                                        .addGap(41, 41, 41)
                                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(x5x1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(x4x1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(x3x1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(x2x1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(panelChargerLayout.createSequentialGroup()
                                .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(x9x1)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(x8x1)
                                    .addGroup(panelChargerLayout.createSequentialGroup()
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(43, 43, 43)
                        .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelChargerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(x1x2)
                                .addComponent(x1x1, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCreerCVS)
                .addContainerGap())
        );

        textFieldName.getAccessibleContext().setAccessibleName("");

        panelChargerMain.add(panelCharger, "card2");

        panelCreateMain.setLayout(new java.awt.CardLayout());

        fileChooser.setCurrentDirectory(new java.io.File("F:\\Documents\\NetBeansProjects\\LeGrosDebrouillard\\src\\CSV"));
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickFileChooser(evt);
            }
        });

        javax.swing.GroupLayout panelCreateLayout = new javax.swing.GroupLayout(panelCreate);
        panelCreate.setLayout(panelCreateLayout);
        panelCreateLayout.setHorizontalGroup(
            panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        panelCreateLayout.setVerticalGroup(
            panelCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        panelCreateMain.add(panelCreate, "card2");

        javax.swing.GroupLayout panelLayoutLayout = new javax.swing.GroupLayout(panelLayout);
        panelLayout.setLayout(panelLayoutLayout);
        panelLayoutLayout.setHorizontalGroup(
            panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAcceuilMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelJeuMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelChargerMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayoutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCreateMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelLayoutLayout.setVerticalGroup(
            panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAcceuilMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayoutLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelJeuMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelChargerMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayoutLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelCreateMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panelLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onClickBandeauButtonLoad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickBandeauButtonLoad
        this.buttonLoad.setSelected(false);
        panelLayout.removeAll();
        panelLayout.add(panelCreateMain);
        panelLayout.repaint();
        panelLayout.revalidate();
    }//GEN-LAST:event_onClickBandeauButtonLoad
    
    private void functionDeMerde(String file) {
        int cpt = 0 ;
        
        try {
        FileWriter fw = new FileWriter(file,true);
        

        if(this.x1x1.isSelected()) {
            String ligne = cpt + "," + 1 + "," + 1 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x1x2.isSelected()) {
            String ligne = cpt + "," + 1 + "," + 2 + "\n";
            fw.write(ligne);
            cpt++;;
        }
        
        if(this.x1x3.isSelected()) {
           String ligne = cpt + "," + 1 + "," + 3 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x1x4.isSelected()) {
            String ligne = cpt + "," + 1 + "," + 4 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x1x5.isSelected()) {
            String ligne = cpt + "," + 1 + "," + 5 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x1x6.isSelected()) {
            String ligne = cpt + "," + 1 + "," + 6 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x1x7.isSelected()) {
            String ligne = cpt + "," + 1 + "," + 7 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x1x8.isSelected()) {
            String ligne = cpt + "," + 1 + "," + 8 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x1x9.isSelected()) {
            String ligne = cpt + "," + 1 + "," + 9 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x2x1.isSelected()) {
            String ligne = cpt + "," + 2 + "," + 1 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x2x2.isSelected()) {
            String ligne = cpt + "," + 2 + "," + 2 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x2x3.isSelected()) {
            String ligne = cpt + "," + 2 + "," + 3 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x2x4.isSelected()) {
            String ligne = cpt + "," + 2 + "," + 4 + "\n";
            fw.write(ligne);
            cpt++;
        }
        else if(this.x2x5.isSelected()) {
            String ligne = cpt + "," + 2 + "," + 5 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x2x6.isSelected()) {
            String ligne = cpt + "," + 2 + "," + 6 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x2x7.isSelected()) {
            String ligne = cpt + "," + 2 + "," + 7 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x2x8.isSelected()) {
            String ligne = cpt + "," + 2 + "," + 8 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x2x9.isSelected()) {
            String ligne = cpt + "," + 2 + "," + 9 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x3x1.isSelected()) {
            String ligne = cpt + "," + 3 + "," + 1 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x3x2.isSelected()) {
            String ligne = cpt + "," + 3 + "," + 2 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x3x3.isSelected()) {
            String ligne = cpt + "," + 3 + "," + 3 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x3x4.isSelected()) {
            String ligne = cpt + "," + 3 + "," + 4 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x3x5.isSelected()) {
            String ligne = cpt + "," + 3 + "," + 5 + "\n";
            fw.write(ligne);
            cpt++;
        }
       
        if(this.x3x6.isSelected()) {
            String ligne = cpt + "," + 3 + "," + 6 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x3x7.isSelected()) {
            String ligne = cpt + "," + 3 + "," + 7 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x3x8.isSelected()) {
            String ligne = cpt + "," + 3 + "," + 8 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x3x9.isSelected()) {
            String ligne = cpt + "," + 3 + "," + 9 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x4x1.isSelected()) {
            String ligne = cpt + "," + 4 + "," + 1 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x4x2.isSelected()) {
            String ligne = cpt + "," + 4 + "," + 2 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x4x3.isSelected()) {
            String ligne = cpt + "," + 4 + "," + 3 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x4x4.isSelected()) {
            String ligne = cpt + "," + 4 + "," + 4 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x4x5.isSelected()) {
            String ligne = cpt + "," + 4 + "," + 5 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x4x6.isSelected()) {
            String ligne = cpt + "," + 4 + "," + 6 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x4x7.isSelected()) {
            String ligne = cpt + "," + 4 + "," + 7 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x4x8.isSelected()) {
            String ligne = cpt + "," + 4 + "," + 8 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x4x9.isSelected()) {
            String ligne = cpt + "," + 4 + "," + 9 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x5x1.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 1 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x5x2.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 2 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x5x3.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 3 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x5x4.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 4 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x5x5.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 5 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x5x6.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 6 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x5x7.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 7 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x5x8.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 8 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x5x9.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 9 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x6x1.isSelected()) {
            String ligne = cpt + "," + 6 + "," + 1 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x6x2.isSelected()) {
            String ligne = cpt + "," + 6 + "," + 2 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x6x3.isSelected()) {
            String ligne = cpt + "," + 6 + "," + 3 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x6x4.isSelected()) {
            String ligne = cpt + "," + 6 + "," + 4 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x6x5.isSelected()) {
            String ligne = cpt + "," + 6 + "," + 5 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x6x6.isSelected()) {
            String ligne = cpt + "," + 6 + "," + 6 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x6x7.isSelected()) {
            String ligne = cpt + "," + 6 + "," + 7 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x6x8.isSelected()) {
            String ligne = cpt + "," + 6 + "," + 8 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x6x9.isSelected()) {
            String ligne = cpt + "," + 6 + "," + 9 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x7x1.isSelected()) {
            String ligne = cpt + "," + 7 + "," + 1 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x7x2.isSelected()) {
            String ligne = cpt + "," + 7 + "," + 2 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x7x3.isSelected()) {
            String ligne = cpt + "," + 7 + "," + 3 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x7x4.isSelected()) {
            String ligne = cpt + "," + 7 + "," + 4 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x7x5.isSelected()) {
            String ligne = cpt + "," + 7 + "," + 5 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x7x6.isSelected()) {
            String ligne = cpt + "," + 7 + "," + 6 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x7x7.isSelected()) {
            String ligne = cpt + "," + 7 + "," + 7 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x7x8.isSelected()) {
            String ligne = cpt + "," + 7 + "," + 8 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x7x9.isSelected()) {
            String ligne = cpt + "," + 7 + "," + 9 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x8x1.isSelected()) {
            String ligne = cpt + "," + 8 + "," + 1 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x8x2.isSelected()) {
            String ligne = cpt + "," + 8 + "," + 2 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x8x3.isSelected()) {
            String ligne = cpt + "," + 8 + "," + 3 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x8x4.isSelected()) {
            String ligne = cpt + "," + 8 + "," + 4 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x8x5.isSelected()) {
            String ligne = cpt + "," + 8 + "," + 5 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x8x6.isSelected()) {
            String ligne = cpt + "," + 8 + "," + 6 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x8x7.isSelected()) {
            String ligne = cpt + "," + 8 + "," + 7 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x8x8.isSelected()) {
            String ligne = cpt + "," + 8 + "," + 8 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x9x1.isSelected()) {
            String ligne = cpt + "," + 9 + "," + 1 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x9x2.isSelected()) {
            String ligne = cpt + "," + 9 + "," + 2 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x9x3.isSelected()) {
            String ligne = cpt + "," + 9 + "," + 3 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x9x4.isSelected()) {
            String ligne = cpt + "," + 9 + "," + 4 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x9x5.isSelected()) {
            String ligne = cpt + "," + 9 + "," + 5 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x9x6.isSelected()) {
            String ligne = cpt + "," + 9 + "," + 6 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x9x7.isSelected()) {
            String ligne = cpt + "," + 9 + "," + 7 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x9x8.isSelected()) {
            String ligne = cpt + "," + 9 + "," + 8 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x9x9.isSelected()) {
            String ligne = cpt + "," + 9 + "," + 9 + "\n";
            fw.write(ligne);
            cpt++;
        }
        
        if(this.x8x9.isSelected()) {
            String ligne = cpt + "," + 5 + "," + 9 + "\n";
            fw.write(ligne);
            cpt++;
        }
        fw.close();
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    private void remplirCSV(String nameFile) {
        try {
            String tmp = "F:\\Documents\\NetBeansProjects\\LeGrosDebrouillard\\src\\CSV\\" ;
            tmp += nameFile ;
            tmp += ".csv" ;
            System.out.println(tmp);
            File f = new File(tmp);
            
            if(f.createNewFile()) {
                System.out.println("crée un fichier");
                this.functionDeMerde(tmp);
            }
            else {
                JOptionPane.showMessageDialog(null,"Un fichier existe déjà");
            }
        }
        catch(Exception e) {
            e.printStackTrace();
        }        
    }
    
    private void buttonCreerCVSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreerCVSActionPerformed
        this.buttonCreerCVS.setSelected(false);
        String name = this.textFieldName.getText().toString() ;
        if(name.equals("")) {
            JOptionPane.showMessageDialog(null,"Un nom de fichier doit être remplit");
        }
        else {
            if(name.contains(".csv")) {
                JOptionPane.showMessageDialog(null,"Veuillez ne pas mettre d'extension");
            }
            else {
                this.remplirCSV(name);
            }
        }
    }//GEN-LAST:event_buttonCreerCVSActionPerformed

    private void onClickBandeauButtonPlay(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickBandeauButtonPlay
        this.buttonPlay.setSelected(false);
        panelLayout.removeAll();
        panelLayout.add(panelJeuMain);
        model = new TSPModel_PtiDeb(this);
       
        try {
            FileReader fr = new FileReader(path);
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                model.addPoint(Integer.parseInt(values[0]), Integer.parseInt(values[1]), Integer.parseInt(values[2]));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        panelLayout.repaint();
        panelLayout.revalidate();
        remplirGraph();
    }//GEN-LAST:event_onClickBandeauButtonPlay

    private void onClickBandeauButtonQuit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickBandeauButtonQuit
        System.exit(0);
    }//GEN-LAST:event_onClickBandeauButtonQuit

    private void onClickPlayPauseButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickPlayPauseButton
        this.buttonPlayPauseJeu.setSelected(false);
        if(!begin) {
            ImageIcon imagePlay = new ImageIcon("F:\\Documents\\NetBeansProjects\\LeGrosDebrouillard\\src\\Images\\pause.png") ;
            this.buttonPlayPauseJeu.setIcon(imagePlay);
            begin = true ;
            thread = new Thread(model) ;
            thread.start();
            return ;
        }
       
        if(stop) {
            ImageIcon imagePlay = new ImageIcon("F:\\Documents\\NetBeansProjects\\LeGrosDebrouillard\\src\\Images\\play.png") ;
            this.buttonPlayPauseJeu.setIcon(imagePlay);
            stop = false ;
            System.out.println(stop);
            model.setPause(true) ;
            return ;
        }
        else {
            ImageIcon imagePlay = new ImageIcon("F:\\Documents\\NetBeansProjects\\LeGrosDebrouillard\\src\\Images\\pause.png") ;
            this.buttonPlayPauseJeu.setIcon(imagePlay);
            stop = true ;
            System.out.println(stop);
            
            synchronized(model) {
                model.setPause(false) ;
                model.notify();
            }
            
            return ;
        }
    }//GEN-LAST:event_onClickPlayPauseButton

    private void onClickRetourRapide(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickRetourRapide
        this.buttonRetourRapideJeu.setSelected(false);
        this.wait += 200 ;
    }//GEN-LAST:event_onClickRetourRapide

    private void onClickButtonAvanceRapide(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickButtonAvanceRapide
        this.buttonAvanceRapideJeu.setSelected(false);
        this.wait -= 200 ;
    }//GEN-LAST:event_onClickButtonAvanceRapide

    private void onClickFileChooser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickFileChooser
       this.path = this.fileChooser.getSelectedFile().getAbsolutePath();
       String ligne = "Voici le fichier que vous avez choisis : " + this.fileChooser.getSelectedFile().getName() ;
       JOptionPane.showMessageDialog(null,ligne);
       recommencerJeu();
    }//GEN-LAST:event_onClickFileChooser

    private void onClickBandeauButtonCreate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickBandeauButtonCreate
        this.buttonLoad.setSelected(false);
        panelLayout.removeAll();
        panelLayout.add(panelChargerMain);
        panelLayout.repaint();
        panelLayout.revalidate();
    }//GEN-LAST:event_onClickBandeauButtonCreate

    private void recommencerJeu() {
        this.current.clear();
        this.best.clear();

        for (Node n : current){
            Iterator<Edge> it = n.getEdgeIterator();
            while (it.hasNext()) {
                it.next();
                it.remove(); 
            }
        }

        for (Node n : best){
            Iterator<Edge> it = n.getEdgeIterator();
            while (it.hasNext()) {
                it.next();
                it.remove();
            }
        }
        
        model = new TSPModel_PtiDeb(this);
        model.clear();
        
        try {
            FileReader fr = new FileReader(path);
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                model.addPoint(Integer.parseInt(values[0]), Integer.parseInt(values[1]), Integer.parseInt(values[2]));
                System.out.println(line);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        remplirGraph();
        thread = new Thread(model);
        model.setPause(true);
        thread.start();
        
        panelLayout.removeAll();
        panelLayout.add(panelJeuMain);
        panelLayout.repaint();
        panelLayout.revalidate();
        
        ImageIcon imagePlay = new ImageIcon("F:\\Documents\\NetBeansProjects\\LeGrosDebrouillard\\src\\Images\\play.png") ;
        this.buttonPlayPauseJeu.setIcon(imagePlay);
        this.stop = false ;
    }
    
    private void buttonRecommencerJeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRecommencerJeuActionPerformed
        this.recommencerJeu();
    }//GEN-LAST:event_buttonRecommencerJeuActionPerformed

    private void buttonArretJeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonArretJeuActionPerformed
        this.best.clear() ;
        this.current.clear();
    }//GEN-LAST:event_buttonArretJeuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plateau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plateau().setVisible(true);
            }
        });
    }
    
    private void lireFichierCSV() {
        try {
            FileReader fr = new FileReader(path);
            BufferedReader br = new BufferedReader(fr);
            String line;
            while ((line = br.readLine()) != null) {
                String[] values = line.split(",");
                Node node = this.best.addNode(String.valueOf(Integer.parseInt(values[0]))) ;
                Node nodeC = this.current.addNode(String.valueOf(Integer.parseInt(values[0]))) ;
                node.setAttribute("xy", Integer.parseInt(values[1]), Integer.parseInt(values[2]));
                nodeC.setAttribute("xy", Integer.parseInt(values[1]), Integer.parseInt(values[2]));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void remplirGraph() {
        this.lireFichierCSV();
        this.best.addAttribute("ui.quality");
        this.best.addAttribute("ui.antialias");
        this.current.addAttribute("ui.quality");
        this.current.addAttribute("ui.antialias");
        
        this.best.setAutoCreate(true);
        this.best.setStrict(true);
        Viewer viewer = new Viewer(this.best, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        viewer.addDefaultView(false);
        ViewPanel viewPanel = viewer.addDefaultView(false);
        bestGraph.add(viewPanel);
        panelJeu.add(bestGraph) ;
        panelJeuMain.add(panelJeu) ;
        panelLayout.add(panelJeuMain);
        
        this.current.setAutoCreate(true);
        this.current.setStrict(true);
        Viewer viewerV2 = new Viewer(this.current, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        viewerV2.addDefaultView(false);
        ViewPanel viewPanelV2 = viewerV2.addDefaultView(false);
        currentGraph.add(viewPanelV2);
        panelJeu.add(currentGraph) ;
        panelJeuMain.add(panelJeu) ;
        panelLayout.add(panelJeuMain);
        
        this.add(panelLayout);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof TSPModel_PtiDeb) {
            TSPModel_PtiDeb model = (TSPModel_PtiDeb) o;
            int id = model.getSegmentID();
            int p1 = model.getSegmentP1();
            int p2 = model.getSegmentP2();
            switch (model.getAction()) {
                case Add:
                    addToGraph(id, p1, p2);
                    break;
                case Remove:
                    removeFromGraph(id);
                    break;
                case NewBest:
                    updateBest();
                    break;
                case Finish:
                    finish();
                    break;
            }
            
            try {
                Thread.sleep(wait);
            }
            catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    public void addToGraph(int id, int p1, int p2) {
        this.current.addEdge(Integer.toString(id), Integer.toString(p1), Integer.toString(p2));
    }

    public void removeFromGraph(int id) {
        this.current.removeEdge(Integer.toString(id));
    }

    public void updateBest() {
        while(this.best.getEdgeCount() > 0) {
            this.best.removeEdge(0);
        }
        
        for (Edge edge : this.current.getEachEdge()) {
            this.best.addEdge(edge.getId(), edge.getSourceNode().getId(), edge.getTargetNode().getId());
        }
    }

    public void finish() {
        System.out.println("Fini");
        JOptionPane.showMessageDialog(null,"Fini");
    }
    
    private Integer wait = 300 ;
    private boolean begin = false ;
    private boolean stop = true ;
    TSPModel_PtiDeb model ;
    Thread thread ;
    private String path = "F:\\Documents\\NetBeansProjects\\LeGrosDebrouillard\\src\\CSV\\Default.csv" ;
    private Graph current = new SingleGraph("current");
    private Graph best = new SingleGraph("best");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bestGraph;
    private javax.swing.JToggleButton buttonArretJeu;
    private javax.swing.JToggleButton buttonAvanceRapideJeu;
    private javax.swing.JToggleButton buttonCreate;
    private javax.swing.JToggleButton buttonCreerCVS;
    private javax.swing.JToggleButton buttonLoad;
    private javax.swing.JToggleButton buttonPlay;
    private javax.swing.JToggleButton buttonPlayPauseJeu;
    private javax.swing.JToggleButton buttonQuit;
    private javax.swing.JToggleButton buttonRecommencerJeu;
    private javax.swing.JToggleButton buttonRetourRapideJeu;
    private javax.swing.JPanel currentGraph;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel panelAcceuil;
    private javax.swing.JPanel panelAcceuilMain;
    private javax.swing.JPanel panelBandeau;
    private javax.swing.JPanel panelCharger;
    private javax.swing.JPanel panelChargerMain;
    private javax.swing.JPanel panelCreate;
    private javax.swing.JPanel panelCreateMain;
    private javax.swing.JPanel panelJeu;
    private javax.swing.JPanel panelJeuMain;
    private javax.swing.JPanel panelLayout;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JRadioButton x1x1;
    private javax.swing.JRadioButton x1x2;
    private javax.swing.JRadioButton x1x3;
    private javax.swing.JRadioButton x1x4;
    private javax.swing.JRadioButton x1x5;
    private javax.swing.JRadioButton x1x6;
    private javax.swing.JRadioButton x1x7;
    private javax.swing.JRadioButton x1x8;
    private javax.swing.JRadioButton x1x9;
    private javax.swing.JRadioButton x2x1;
    private javax.swing.JRadioButton x2x2;
    private javax.swing.JRadioButton x2x3;
    private javax.swing.JRadioButton x2x4;
    private javax.swing.JRadioButton x2x5;
    private javax.swing.JRadioButton x2x6;
    private javax.swing.JRadioButton x2x7;
    private javax.swing.JRadioButton x2x8;
    private javax.swing.JRadioButton x2x9;
    private javax.swing.JRadioButton x3x1;
    private javax.swing.JRadioButton x3x2;
    private javax.swing.JRadioButton x3x3;
    private javax.swing.JRadioButton x3x4;
    private javax.swing.JRadioButton x3x5;
    private javax.swing.JRadioButton x3x6;
    private javax.swing.JRadioButton x3x7;
    private javax.swing.JRadioButton x3x8;
    private javax.swing.JRadioButton x3x9;
    private javax.swing.JRadioButton x4x1;
    private javax.swing.JRadioButton x4x2;
    private javax.swing.JRadioButton x4x3;
    private javax.swing.JRadioButton x4x4;
    private javax.swing.JRadioButton x4x5;
    private javax.swing.JRadioButton x4x6;
    private javax.swing.JRadioButton x4x7;
    private javax.swing.JRadioButton x4x8;
    private javax.swing.JRadioButton x4x9;
    private javax.swing.JRadioButton x5x1;
    private javax.swing.JRadioButton x5x2;
    private javax.swing.JRadioButton x5x3;
    private javax.swing.JRadioButton x5x4;
    private javax.swing.JRadioButton x5x5;
    private javax.swing.JRadioButton x5x6;
    private javax.swing.JRadioButton x5x7;
    private javax.swing.JRadioButton x5x8;
    private javax.swing.JRadioButton x5x9;
    private javax.swing.JRadioButton x6x1;
    private javax.swing.JRadioButton x6x2;
    private javax.swing.JRadioButton x6x3;
    private javax.swing.JRadioButton x6x4;
    private javax.swing.JRadioButton x6x5;
    private javax.swing.JRadioButton x6x6;
    private javax.swing.JRadioButton x6x7;
    private javax.swing.JRadioButton x6x8;
    private javax.swing.JRadioButton x6x9;
    private javax.swing.JRadioButton x7x1;
    private javax.swing.JRadioButton x7x2;
    private javax.swing.JRadioButton x7x3;
    private javax.swing.JRadioButton x7x4;
    private javax.swing.JRadioButton x7x5;
    private javax.swing.JRadioButton x7x6;
    private javax.swing.JRadioButton x7x7;
    private javax.swing.JRadioButton x7x8;
    private javax.swing.JRadioButton x7x9;
    private javax.swing.JRadioButton x8x1;
    private javax.swing.JRadioButton x8x2;
    private javax.swing.JRadioButton x8x3;
    private javax.swing.JRadioButton x8x4;
    private javax.swing.JRadioButton x8x5;
    private javax.swing.JRadioButton x8x6;
    private javax.swing.JRadioButton x8x7;
    private javax.swing.JRadioButton x8x8;
    private javax.swing.JRadioButton x8x9;
    private javax.swing.JRadioButton x9x1;
    private javax.swing.JRadioButton x9x2;
    private javax.swing.JRadioButton x9x3;
    private javax.swing.JRadioButton x9x4;
    private javax.swing.JRadioButton x9x5;
    private javax.swing.JRadioButton x9x6;
    private javax.swing.JRadioButton x9x7;
    private javax.swing.JRadioButton x9x8;
    private javax.swing.JRadioButton x9x9;
    // End of variables declaration//GEN-END:variables
}
